name: password_file_write
run-name: ${{ github.actor }} is running the password_file_write
on: [manual]
jobs:
  setup-variables:
    runs-on: ubuntu-latest
    outputs:
      filename_now: ${{steps.set_vars.outputs.filename_now}}
      iso_now: ${{steps.set_vars.outputs.iso_now}}
      artifact_name: ${{steps.artifact_name.outputs.artifact_name}}
    steps:
      - name: set variables
        id: set_vars
        shell: bash
        run: |
          echo "filename_now=passwords_$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
          echo "iso_now=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: set artifact_name
        id: artifact_name
        run: |
          echo "artifact_name=${{steps.set_vars.outputs.filename_now}}-${{github.event.repository.name}}-${{github.workflow}}-${{github.sha}}" >> $GITHUB_OUTPUT
  write_passwords:
    needs: setup-variables
    runs-on: ubuntu-latest
    env:
      OUTPUT_FILE: "outputs/${{github.job}}_output.txt"
      PASSWORD: ${{secrets.MY_TOP_SECRET}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: create directory for output
        run: mkdir -p outputs
      - name: set up file header block
        run: |
          echo "*********************" >> $OUTPUT_FILE
          echo "workflow information" >> $OUTPUT_FILE
          echo "workflow: ${{github.workflow}}" >> $OUTPUT_FILE
          echo "job: ${{github.job}}" >> $OUTPUT_FILE
          echo "github_actor: ${{github.actor}}" >> $OUTPUT_FILE
          echo "timestamp: ${{needs.setup-variables.outputs.iso_now}}" >> $OUTPUT_FILE
          echo "*********************" >> $OUTPUT_FILE
          echo "passwords:" >> $OUTPUT_FILE
          echo "MY_TOP_SECRET=${{secrets.MY_TOP_SECRET}}" >> $OUTPUT_FILE
          echo "MY_TOP_SECRET_IN_ENV=$PASSWORD" >> $OUTPUT_FILE
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.setup-variables.outputs.artifact_name }}
          path: ${{env.OUTPUT_FILE}}
